source 'https://rubygems.org'

gem 'rails', github: "rails/rails", branch: "4-2-stable"

# Use postgresql as the database for Active Record
gem 'pg'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Bootstrap-saas for using bootstrap in this app
gem 'bootstrap-sass'
# Pagination, check for themes like bootstrap/foundation: https://github.com/amatsuda/kaminari_themes.
gem 'kaminari'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'

# gem for make fake users
gem 'faker'

# Use Passenger as the app server
gem 'passenger', '~> 5.0.9'

# Use Unicorn as the app server
# gem 'unicorn-rails'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Heroku lib dependency
gem 'rails_12factor', group: :production

group :development, :test do
	# Call 'byebug' anywhere in the code to stop execution and get a debugger console
	gem 'byebug'
	gem "ruby-debug-passenger" # Run 'rake debug' to restart passenger with byebug connected.

	# Access an IRB console on exception pages or by using <%= console %> in views
	gem 'web-console', '~> 2.0'

	# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
	gem 'spring'
	gem 'spring-commands-rspec' # Enables it for RSpec

	 # Rspec
	gem 'rspec-rails'
	gem 'kaminari-rspec'

	# Progress bar for Rspec, watch .rspec file in home
	gem 'fuubar'

	# Factory for fixtures (Data for tests.)
	gem 'factory_girl_rails'

	# Simulate user interaction with browser.
	gem 'capybara'

	# Used to launch clients like the browser or emails (add save_and_open_page anywhere in a test.)
	gem 'launchy'

	# Guard-rspec for automated rspec testing.
	gem 'guard-rspec', require: false

	# Guard-livereload for automated browser reload on view changes.
	gem 'guard-livereload', require: false

	# Pry for debbuging errors
	gem 'pry'
end

